#!/usr/bin/env sh
## HYPER == SHIFT + CMD + ALT + OPTION

## Quickly restart the yabai launch agent
ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

## open terminal
hyper - return : /Applications/Alacritty.app/Contents/MacOS/alacritty
hyper - m : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu"
hyper - t : /Users/italo/.config/yabai/toggle-bar.sh
# hyper - b : open /Users/italo/Personal/AppData/Burp/burpsuite_community_1.7.33.jar
hyper - r : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu" -e "/Users/italo/Personal/Programing/Repos/github.com/italoaa/GhqSearch/ghqsearch"
hyper - s : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu" --config-file ~/.config/alacritty/Launcha.yml -e 'btm'
hyper - n : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu" -e 'ncmpcpp'
# This is one of my favourites
hyper - c : /Users/italo/.config/Bin/fun/classic-radio.sh

# focus
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Moving windows
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# Reziese
cmd + alt - h : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
cmd + alt - j : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
cmd + alt - k : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
cmd + alt - l : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

# Rotate windows clockwise and anticlockwise
alt - r         : yabai -m space --rotate 270
shift + alt - r : yabai -m space --rotate 90

# Fullscreen
hyper - f : yabai -m window --toggle zoom-fullscreen

# enable / Disable gaps in current workspace
cmd + alt + shift - g : yabai -m space --toggle padding; yabai -m space --toggle gap

## float / unfloat window and center on screen
alt - t : yabai -m window --toggle float

## create desktop, move window and follow focus
shift + cmd - n : yabai -m space --create \
set index (yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index') && \
yabai -m window --space "$index" && \
yabai -m space --focus "$index"

## create desktop and follow focus
shift + alt - n : yabai -m space --create && \
set index (yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index') && \
yabai -m space --focus "$index"

## destroy desktop
ctrl - backspace : yabai -m space --destroy

## fast focus desktop
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9

## move window and focus to other space
hyper - 1 : yabai -m window --space  1; yabai -m space --focus 1
hyper - 2 : yabai -m window --space  2; yabai -m space --focus 2
hyper - 3 : yabai -m window --space  3; yabai -m space --focus 3
hyper - 4 : yabai -m window --space  4; yabai -m space --focus 4
hyper - 5 : yabai -m window --space  5; yabai -m space --focus 5
hyper - 6 : yabai -m window --space  6; yabai -m space --focus 6
hyper - 7 : yabai -m window --space  7; yabai -m space --focus 7
hyper - 8 : yabai -m window --space  8; yabai -m space --focus 8
hyper - 9 : yabai -m window --space  9; yabai -m space --focus 9
