#!/usr/bin/env sh
## HYPER == SHIFT + CMD + ALT + OPTION

## Quickly restart the yabai launch agent
ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"

## open terminal
hyper - return : /Applications/Alacritty.app/Contents/MacOS/alacritty
hyper - m : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu"
hyper - e : emacs --with-profile nano -dark
# hyper - q : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu" -e "/Users/italo/Personal/Programing/Repos/github.com/italoaa/Kuiqer/kuiqer.sh"
# hyper - b : open /Users/italo/Personal/AppData/Burp/burpsuite_community_1.7.33.jar
# hyper - n : notflix
hyper - r : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu" -e "/Users/italo/Personal/Programing/Repos/github.com/italoaa/GhqSearch/ghqsearch"
hyper - s : /Applications/Alacritty.app/Contents/MacOS/alacritty -t "Menu" --config-file ~/.config/alacritty/Launcha.yml -e 'btm'
hyper - c : /Users/italo/.config/Bin/fun/classic-radio.sh

## swap window
cmd + alt - h : yabai -m window --swap west
cmd + alt - j : yabai -m window --swap south
cmd + alt - k : yabai -m window --swap north
cmd + alt - l : yabai -m window --swap east

## rotate tree 90
hyper - r : yabai -m space --rotate 90

hyper - f : yabai -m window --toggle zoom-fullscreen

# Enable / Disable gaps in current workspace
cmd + alt - g : yabai -m space --toggle padding; yabai -m space --toggle gap

# Equalize size of windows
cmd + alt - e : yabai -m space --balance

## move window and focus to other space
hyper - 1 : yabai -m window --space  1; yabai -m space --focus 1
hyper - 2 : yabai -m window --space  2; yabai -m space --focus 2
hyper - 3 : yabai -m window --space  3; yabai -m space --focus 3
hyper - 4 : yabai -m window --space  4; yabai -m space --focus 4
hyper - 5 : yabai -m window --space  5; yabai -m space --focus 5
hyper - 6 : yabai -m window --space  6; yabai -m space --focus 6
hyper - 7 : yabai -m window --space  7; yabai -m space --focus 7
hyper - 8 : yabai -m window --space  8; yabai -m space --focus 8
hyper - 9 : yabai -m window --space  9; yabai -m space --focus 9

# cycle through windows
# cycle backwards
hyper - i : yabai -m query --spaces | jq -re ".[] | select(.visible == 1).index" | xargs -I{} yabai -m query --windows --space {} | jq -sre "add | sort_by(.display, .frame.x, .frame.y, .id) | nth(index(map(select(.focused == 1))) - 1).id" | xargs -I{} yabai -m window --focus {}
hyper - o : yabai -m query --spaces | jq -re ".[] | select(.visible == 1).index" | xargs -I{} yabai -m query --windows --space {} | jq -sre "add | sort_by(.display, .frame.x, .frame.y, .id) | reverse | nth(index(map(select(.focused == 1))) - 1).id" | xargs -I{} yabai -m window --focus {}


## float / unfloat window and center on screen
alt - t : yabai -m window --toggle float;\
#yabai -m window --grid 4:4:1:1:2:2 
## toggle sticky 
# alt - s : yabai -m window --toggle sticky 
## toggle sticky, float and resize to picture-in-picture size 
# alt - p : yabai -m window --toggle sticky;\ yabai -m window --grid 5:5:4:0:1:1 
## change layout of desktop 
# ctrl + alt - a : yabai -m space --layout bsp ctrl + alt - d : yabai -m space --layout float

## toggle window split type
#alt - e : yabai -m window --toggle split

## toggle window border
# shift + alt - b : yabai -m window --toggle border

# Reziese
cmd + alt - a : yabai -m window --resize left:-50:0; \
                  yabai -m window --resize right:-50:0
cmd + alt - s : yabai -m window --resize bottom:0:50; \
                  yabai -m window --resize top:0:50
cmd + alt - w : yabai -m window --resize top:0:-50; \
                  yabai -m window --resize bottom:0:-50
cmd + alt - d : yabai -m window --resize right:50:0; \
                  yabai -m window --resize left:50:0

## create desktop, move window and follow focus
shift + cmd - n : yabai -m space --create && \
set index (yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index') && \
yabai -m window --space "$index" && \
yabai -m space --focus "$index"

## create desktop and follow focus
shift + alt - n : yabai -m space --create && \
set index (yabai -m query --spaces --display | jq 'map(select(."native-fullscreen" == 0))[-1].index') && \
yabai -m space --focus "$index"

## destroy desktop
hyper - backspace : yabai -m space --destroy

## fast focus desktop
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9


# move window
shift + ctrl - a : yabai -m window --move rel:-20:0
shift + ctrl - s : yabai -m window --move rel:0:20
shift + ctrl - w : yabai -m window --move rel:0:-20
shift + ctrl - d : yabai -m window --move rel:22:0

# -----------------------------------
# Stacks
# ----------------------------------- 
# Focus window up/down in stack
hyper - n : yabai -m window --focus stack.next
hyper - p : yabai -m window --focus stack.prev

# Add the active window  to the window or stack to the {direction}
# Note that this only works when the active window does *not* already belong to a stack
cmd + alt + shift - l  : yabai -m window west --stack (yabai -m query --windows --window | jq -r '.id')
cmd + alt + shift - h  : yabai -m window south --stack (yabai -m query --windows --window | jq -r '.id')
cmd + alt + shift - k    : yabai -m window north --stack (yabai -m query --windows --window | jq -r '.id')
cmd + alt + shift - j : yabai -m window east --stack (yabai -m query --windows --window | jq -r '.id')
