#!/usr/bin/env sh
#YABAI STUFF
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

CBACK='111318'
CFORE='d8d5d8'
CINSE='d8d5d8'

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on  manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on  manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on  manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on  manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on  manage=off
yabai -m rule --add app="^System Information$" sticky=on  manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on  manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="qemu" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add title='^Menu$' manage=off sticky=on  #Custom launcher
yabai -m rule --add title='^Rioki$' manage=off #Custom launcher

yabai -m config window_placement second_child
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
yabai -m config mouse_modifier cmd
yabai -m config mouse_action2 resize
yabai -m config mouse_action1 move
yabai -m config insert_feedback_color 0xffd75f5f

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5
 
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

echo "yabai configuration loaded.."

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
