#!/usr/bin/env sh
#YABAI STUFF
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

CBACK='111318'
CFORE='d8d5d8'
CINSE='d8d5d8'

#names used in other scripts
yabai -m space 1 --label Term
yabai -m space 2 --label Chrome
yabai -m space 3 --label Zoom
yabai -m space 4 --label Notes
yabai -m space 5 --label Chat
yabai -m space 6 --label Discord
yabai -m space 7 --label Mail
yabai -m space 8 --label Music
yabai -m space 9 --label Cal
yabai -m space 10 --label Misc

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on  manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on  manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on  manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on  manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on  manage=off
yabai -m rule --add app="^System Information$" sticky=on  manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on  manage=off
yabai -m rule --add app="^console$" manage=off
# yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="qemu" manage=off
yabai -m rule --add app="^Spark$" manage=off
yabai -m rule --add app="^Microsoft Outlook$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add title='^Menu$' manage=off layer=above sticky=on border=on #Custom launcher

## Some random global settings
# yabai -m config focus_follows_mouse          autoraise
# yabai -m config focus_follows_mouse          on
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00

## built in border
yabai -m config window_border off
yabai -m config window_border on
yabai -m config window_border_blur off
yabai -m config window_border_width 1
yabai -m config window_border_radius 8
yabai -m config active_window_border_color   0xff$CFORE
yabai -m config normal_window_border_color   0x00$CBACK
yabai -m config insert_window_border_color   0x00$CINSE
killall limelight &>/dev/null


yabai -m config auto_balance off
yabai -m config split_ratio 0.50
yabai -m config mouse_modifier cmd
yabai -m config mouse_action2 resize
yabai -m config mouse_action1 move

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 5
yabai -m config bottom_padding 5
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5
 
###################################################
## Bars
###################################################
# yabai -m config status_bar                   on
# yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
# yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
# yabai -m config status_bar_background_color  0xff202020
# yabai -m config status_bar_foreground_color  0xffa8a8a8
# yabai -m config status_bar_space_icon_strip  "(1) web" 2 3 4 5 6 7 8 9 10
# yabai -m config status_bar_power_icon_strip   
# yabai -m config status_bar_space_icon        
# yabai -m config status_bar_clock_icon        time
# spacebar
yabai -m config external_bar off:26:0


yabai -m signal --add event=window_destroyed action="./on_destroy"

yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

echo "yabai configuration loaded.."

# pywal
