(("doom" . ((user-emacs-directory . "~/.config/emacs/")))
 ("light" . ((user-emacs-directory . "~/.config/my-emacs/")))
 ("lambda" . ((user-emacs-directory . "~/.config/lambda-emacs/")))
 ("default" . ((user-emacs-directory . "~/.config/bread")))
 )
